### ISSUE TITLE
Dragaway items and have them reflect the values

### ISSUE THREAD

**Issue by tomdreamevil** [evley/fire#9] opened 2020-02-23 23:48 UTC
#### Feature Description

Dragging away an item from the circle groupings and watch the numbers animate at the same curve excluding the item you've dragged away.

#### Use Case

Easier to view impact for certain items with/without them

**Comment by tinybigideas** [comment] 2020-02-24 08:18
closing as dupe of #3

**Closed by tinybigideas** 2020-02-24 08:18 UTC
